/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;

import MODEL.QL_HoaDon_229;
import SERVICE.QLHoaDon_Service;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QL_HoaDon_JPanelForm extends javax.swing.JPanel {

    private List<QL_HoaDon_229> list = new ArrayList<>();
    DefaultTableModel defaultTableModel;
    QLHoaDon_Service dhService;
    QL_HoaDon_229 dh;
    public QL_HoaDon_JPanelForm() throws SQLException {
        initComponents();
        dhService = new QLHoaDon_Service();
        dh = new QL_HoaDon_229();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tblTTDonDatHang_229.setModel(defaultTableModel);

        defaultTableModel.addColumn("MaDH");
        defaultTableModel.addColumn("NgayTaoDH");
        defaultTableModel.addColumn("DiaChiGiaoHang");
        defaultTableModel.addColumn("PhươngThucThanhToan");
        defaultTableModel.addColumn("ThoiGianGiaoHang");
        defaultTableModel.addColumn("ThoiGianThanhToan");
        defaultTableModel.addColumn("maKH");
        defaultTableModel.addColumn("maNV");
        defaultTableModel.addColumn("maKM");
        
        setTableData(dhService.getAllUsers());

    }

    private void setTableData(List<QL_HoaDon_229> hoadon) {
        for (QL_HoaDon_229 hd : hoadon) {
            defaultTableModel.addRow(new Object[]{hd.getMaDH_229(), hd.getNgayTaoDH_229(),hd.getDiaChiGiaoHang_229(), hd.getPhuongThucThanhToan_229(), hd.getThoiGianThanhToan_229(), hd.getThoiGianGiaoHang_229(),hd.getMaKH_229(),hd.getMaNV_229(),hd.getMaKM_229()});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanelTable_229 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTTDonDatHang_229 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel_TTC_MuaHang_229 = new javax.swing.JPanel();
        jPanel_TTC_229 = new javax.swing.JPanel();
        lblMaDonHang_229 = new javax.swing.JLabel();
        cmbMaDonHang_229 = new javax.swing.JComboBox<>();
        jDateChooserThoiGianBaoHanh_229 = new com.toedter.calendar.JDateChooser();
        lblThoiGianGiaoHang_229 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMaNhanVien_229 = new javax.swing.JLabel();
        cmbMaKhachHang_229 = new javax.swing.JComboBox<>();
        lblMaKhachHang_229 = new javax.swing.JLabel();
        cmbMaNhanVien_229 = new javax.swing.JComboBox<>();
        lblPhuongThucThanhToan_229 = new javax.swing.JLabel();
        cmbPhuongThucThanhToan_229 = new javax.swing.JComboBox<>();
        jDateChooserThoiGianThanhToan_229 = new com.toedter.calendar.JDateChooser();
        lblThoiGianThanhToan_229 = new javax.swing.JLabel();
        txtDiaChiGiaoHang_229 = new javax.swing.JTextField();
        lblNgayTaoDonHang_229 = new javax.swing.JLabel();
        jdcNgayTaoDonHang_229 = new com.toedter.calendar.JDateChooser();
        jPanel_MuaHang_229 = new javax.swing.JPanel();
        txtThanhTien_229 = new javax.swing.JTextField();
        lblThanhTien_229 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblTenSanPham_229 = new javax.swing.JLabel();
        txtTenSanPham_229 = new javax.swing.JTextField();
        lblMaSanPham_229 = new javax.swing.JLabel();
        cmbMaSanPham_229 = new javax.swing.JComboBox<>();
        lblDonGia_229 = new javax.swing.JLabel();
        txtGia_229 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jPanel_Update_229 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel_TimKiem_229 = new javax.swing.JPanel();
        txtTimKiem_229 = new javax.swing.JTextField();
        btnTimKiem_229 = new javax.swing.JButton();
        btnLamMoi_229 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 550));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(880, 538));

        jPanelTable_229.setBackground(new java.awt.Color(204, 255, 204));
        jPanelTable_229.setPreferredSize(new java.awt.Dimension(900, 183));

        tblTTDonDatHang_229.setBackground(new java.awt.Color(204, 204, 204));
        tblTTDonDatHang_229.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Mã Khách Hàng", "Mã sản phẩm", "Mã nhân viên", "Ngày tạo đơn hàng", "Thời gian thanh toán ", "Thời gian giao hàng ", "Tên sản phẩm ", "Số lượng đặt", "Đơn giá ", "Giảm giá ", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tblTTDonDatHang_229);

        javax.swing.GroupLayout jPanelTable_229Layout = new javax.swing.GroupLayout(jPanelTable_229);
        jPanelTable_229.setLayout(jPanelTable_229Layout);
        jPanelTable_229Layout.setHorizontalGroup(
            jPanelTable_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTable_229Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelTable_229Layout.setVerticalGroup(
            jPanelTable_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTable_229Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 229));

        jPanel_TTC_MuaHang_229.setBackground(new java.awt.Color(153, 255, 153));

        jPanel_TTC_229.setBackground(new java.awt.Color(153, 255, 153));
        jPanel_TTC_229.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chung"));

        lblMaDonHang_229.setText("Mã đơn hàng");

        cmbMaDonHang_229.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMaDonHang_229ActionPerformed(evt);
            }
        });

        lblThoiGianGiaoHang_229.setText("Thời gian giao hàng:");

        jLabel3.setText("Địa chỉ giao hàng :");

        lblMaNhanVien_229.setText("Mã nhân viên");

        cmbMaKhachHang_229.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMaKhachHang_229ActionPerformed(evt);
            }
        });

        lblMaKhachHang_229.setText("Mã Khách hàng");

        cmbMaNhanVien_229.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMaNhanVien_229ActionPerformed(evt);
            }
        });

        lblPhuongThucThanhToan_229.setText("Phương thức thanh toán :");

        cmbPhuongThucThanhToan_229.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Thẻ ngân hàng" }));

        lblThoiGianThanhToan_229.setText("Thời gian thanh toán");

        txtDiaChiGiaoHang_229.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiGiaoHang_229ActionPerformed(evt);
            }
        });

        lblNgayTaoDonHang_229.setText("Ngày tạo đơn hàng");

        javax.swing.GroupLayout jPanel_TTC_229Layout = new javax.swing.GroupLayout(jPanel_TTC_229);
        jPanel_TTC_229.setLayout(jPanel_TTC_229Layout);
        jPanel_TTC_229Layout.setHorizontalGroup(
            jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TTC_229Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TTC_229Layout.createSequentialGroup()
                        .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNhanVien_229, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaDonHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaKhachHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMaNhanVien_229, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMaDonHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMaKhachHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TTC_229Layout.createSequentialGroup()
                        .addComponent(lblPhuongThucThanhToan_229, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cmbPhuongThucThanhToan_229, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TTC_229Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel_TTC_229Layout.createSequentialGroup()
                                .addComponent(lblThoiGianGiaoHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserThoiGianBaoHanh_229, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_TTC_229Layout.createSequentialGroup()
                                .addComponent(lblThoiGianThanhToan_229, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserThoiGianThanhToan_229, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_TTC_229Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNgayTaoDonHang_229, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiaChiGiaoHang_229, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jdcNgayTaoDonHang_229, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel_TTC_229Layout.setVerticalGroup(
            jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TTC_229Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaDonHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbMaDonHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDiaChiGiaoHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcNgayTaoDonHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaKhachHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbMaKhachHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNgayTaoDonHang_229)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_TTC_229Layout.createSequentialGroup()
                        .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMaNhanVien_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaNhanVien_229, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPhuongThucThanhToan_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhuongThucThanhToan_229, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThoiGianThanhToan_229, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_TTC_229Layout.createSequentialGroup()
                        .addGroup(jPanel_TTC_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserThoiGianBaoHanh_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThoiGianGiaoHang_229))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserThoiGianThanhToan_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_MuaHang_229.setBackground(new java.awt.Color(153, 255, 153));
        jPanel_MuaHang_229.setBorder(javax.swing.BorderFactory.createTitledBorder("Mua hàng"));

        lblThanhTien_229.setText("Thành tiền :");

        jLabel1.setText("Số lượng đặt");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lblTenSanPham_229.setText("Tên sản phẩm ");

        lblMaSanPham_229.setText("Mã sản phẩm ");

        lblDonGia_229.setText("Đơn giá");

        txtGia_229.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGia_229ActionPerformed(evt);
            }
        });

        jLabel2.setText("Giảm giá");

        javax.swing.GroupLayout jPanel_MuaHang_229Layout = new javax.swing.GroupLayout(jPanel_MuaHang_229);
        jPanel_MuaHang_229.setLayout(jPanel_MuaHang_229Layout);
        jPanel_MuaHang_229Layout.setHorizontalGroup(
            jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MuaHang_229Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSanPham_229, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiamGia)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMaSanPham_229, 0, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MuaHang_229Layout.createSequentialGroup()
                        .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDonGia_229, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenSanPham_229, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGia_229, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txtTenSanPham_229)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MuaHang_229Layout.createSequentialGroup()
                        .addComponent(lblThanhTien_229, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtThanhTien_229, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_MuaHang_229Layout.setVerticalGroup(
            jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MuaHang_229Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MuaHang_229Layout.createSequentialGroup()
                        .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSanPham_229, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMaSanPham_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_MuaHang_229Layout.createSequentialGroup()
                        .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenSanPham_229, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSanPham_229, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonGia_229, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGia_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtThanhTien_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThanhTien_229))))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout jPanel_TTC_MuaHang_229Layout = new javax.swing.GroupLayout(jPanel_TTC_MuaHang_229);
        jPanel_TTC_MuaHang_229.setLayout(jPanel_TTC_MuaHang_229Layout);
        jPanel_TTC_MuaHang_229Layout.setHorizontalGroup(
            jPanel_TTC_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TTC_MuaHang_229Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TTC_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_TTC_229, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_MuaHang_229, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_TTC_MuaHang_229Layout.setVerticalGroup(
            jPanel_TTC_MuaHang_229Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TTC_MuaHang_229Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_TTC_229, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_MuaHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Update_229.setLayout(new java.awt.GridLayout(5, 1));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/plus.png"))); // NOI18N
        jButton1.setText("Thêm");
        jPanel_Update_229.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sua.png"))); // NOI18N
        jButton2.setText("Sửa");
        jPanel_Update_229.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh.png"))); // NOI18N
        jButton3.setText("Đặt lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel_Update_229.add(jButton3);

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/xoa.png"))); // NOI18N
        jButton4.setText("Xóa");
        jPanel_Update_229.add(jButton4);

        jButton5.setBackground(new java.awt.Color(51, 153, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/luu.png"))); // NOI18N
        jButton5.setText("Lưu");
        jPanel_Update_229.add(jButton5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_TTC_MuaHang_229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Update_229, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_TTC_MuaHang_229, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Update_229, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_TimKiem_229.setBackground(new java.awt.Color(153, 255, 153));
        jPanel_TimKiem_229.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 541;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 1, 6, 0);
        jPanel_TimKiem_229.add(txtTimKiem_229, gridBagConstraints);

        btnTimKiem_229.setBackground(new java.awt.Color(51, 153, 0));
        btnTimKiem_229.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem_229.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/search.png"))); // NOI18N
        btnTimKiem_229.setText("Tìm kiếm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 6, 0);
        jPanel_TimKiem_229.add(btnTimKiem_229, gridBagConstraints);

        btnLamMoi_229.setBackground(new java.awt.Color(255, 204, 204));
        btnLamMoi_229.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLamMoi_229.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh.png"))); // NOI18N
        btnLamMoi_229.setText("Làm mới");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 6, 6);
        jPanel_TimKiem_229.add(btnLamMoi_229, gridBagConstraints);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                    .addComponent(jPanel_TimKiem_229, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                    .addComponent(jPanelTable_229, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTable_229, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_TimKiem_229, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMaDonHang_229ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMaDonHang_229ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMaDonHang_229ActionPerformed

    private void txtGia_229ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGia_229ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGia_229ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbMaKhachHang_229ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMaKhachHang_229ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMaKhachHang_229ActionPerformed

    private void cmbMaNhanVien_229ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMaNhanVien_229ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMaNhanVien_229ActionPerformed

    private void txtDiaChiGiaoHang_229ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiGiaoHang_229ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiGiaoHang_229ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi_229;
    private javax.swing.JButton btnTimKiem_229;
    private javax.swing.JComboBox<String> cmbMaDonHang_229;
    private javax.swing.JComboBox<String> cmbMaKhachHang_229;
    private javax.swing.JComboBox<String> cmbMaNhanVien_229;
    private javax.swing.JComboBox<String> cmbMaSanPham_229;
    private javax.swing.JComboBox<String> cmbPhuongThucThanhToan_229;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooserThoiGianBaoHanh_229;
    private com.toedter.calendar.JDateChooser jDateChooserThoiGianThanhToan_229;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelTable_229;
    private javax.swing.JPanel jPanel_MuaHang_229;
    private javax.swing.JPanel jPanel_TTC_229;
    private javax.swing.JPanel jPanel_TTC_MuaHang_229;
    private javax.swing.JPanel jPanel_TimKiem_229;
    private javax.swing.JPanel jPanel_Update_229;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcNgayTaoDonHang_229;
    private javax.swing.JLabel lblDonGia_229;
    private javax.swing.JLabel lblMaDonHang_229;
    private javax.swing.JLabel lblMaKhachHang_229;
    private javax.swing.JLabel lblMaNhanVien_229;
    private javax.swing.JLabel lblMaSanPham_229;
    private javax.swing.JLabel lblNgayTaoDonHang_229;
    private javax.swing.JLabel lblPhuongThucThanhToan_229;
    private javax.swing.JLabel lblTenSanPham_229;
    private javax.swing.JLabel lblThanhTien_229;
    private javax.swing.JLabel lblThoiGianGiaoHang_229;
    private javax.swing.JLabel lblThoiGianThanhToan_229;
    private javax.swing.JTable tblTTDonDatHang_229;
    private javax.swing.JTextField txtDiaChiGiaoHang_229;
    private javax.swing.JTextField txtGia_229;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtTenSanPham_229;
    private javax.swing.JTextField txtThanhTien_229;
    private javax.swing.JTextField txtTimKiem_229;
    // End of variables declaration//GEN-END:variables
}
