/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QL_KhachHang_JPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form QL_KhachHang_PanelForm
     */
    DefaultTableModel defaultTableModel;
    public QL_KhachHang_JPanelForm() {
        initComponents();
         defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tblKhachHang_212.setModel(defaultTableModel);

        defaultTableModel.addColumn("MaKH");
        defaultTableModel.addColumn("HoTen");
        defaultTableModel.addColumn("GioiTinh");
        defaultTableModel.addColumn("SoDienThoai");
        defaultTableModel.addColumn("DiaChi");
    }
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpnThietLapTTKH_212 = new javax.swing.JPanel();
        jPanel2_212 = new javax.swing.JPanel();
        jLabel1_212 = new javax.swing.JLabel();
        jLabel2_212 = new javax.swing.JLabel();
        jLabel3_212 = new javax.swing.JLabel();
        jLabel4_212 = new javax.swing.JLabel();
        jLabel5_212 = new javax.swing.JLabel();
        txtMaKH_212 = new javax.swing.JTextField();
        txtTenKH_212 = new javax.swing.JTextField();
        txtSDT_212 = new javax.swing.JTextField();
        jScrollPane1_212 = new javax.swing.JScrollPane();
        txtAreaDiaChi_212 = new javax.swing.JTextArea();
        radioBtnNam_212 = new javax.swing.JRadioButton();
        radioBtnNu_212 = new javax.swing.JRadioButton();
        jPanel3_212 = new javax.swing.JPanel();
        btnThem_212 = new javax.swing.JButton();
        bthSua_212 = new javax.swing.JButton();
        btnXoa_212 = new javax.swing.JButton();
        btnRefresh_212 = new javax.swing.JButton();
        jpnThongTinKH_212 = new javax.swing.JPanel();
        jpnTimKiem_212 = new javax.swing.JPanel();
        txtTimKiem_212 = new javax.swing.JTextField();
        btnTimKiem_212 = new javax.swing.JButton();
        jScrollPane3_212 = new javax.swing.JScrollPane();
        tblKhachHang_212 = new javax.swing.JTable();
        jpnLoc_212 = new javax.swing.JPanel();
        jLabel6_212 = new javax.swing.JLabel();
        cbxLoc_212 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setBackground(new java.awt.Color(204, 255, 204));

        jpnThietLapTTKH_212.setBackground(new java.awt.Color(204, 255, 204));
        jpnThietLapTTKH_212.setBorder(javax.swing.BorderFactory.createTitledBorder("Thiết lập thông tin khách hàng"));

        jPanel2_212.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1_212.setText("Mã khách hàng");

        jLabel2_212.setText("Tên khách hàng");

        jLabel3_212.setText("Giới tính");

        jLabel4_212.setText("Số điện thoại");

        jLabel5_212.setText("Địa chỉ");

        txtMaKH_212.setPreferredSize(new java.awt.Dimension(150, 28));

        txtTenKH_212.setPreferredSize(new java.awt.Dimension(150, 28));

        txtSDT_212.setPreferredSize(new java.awt.Dimension(150, 28));

        txtAreaDiaChi_212.setColumns(20);
        txtAreaDiaChi_212.setRows(5);
        jScrollPane1_212.setViewportView(txtAreaDiaChi_212);

        buttonGroup1.add(radioBtnNam_212);
        radioBtnNam_212.setText("Nam");

        buttonGroup1.add(radioBtnNu_212);
        radioBtnNu_212.setText("Nữ");

        javax.swing.GroupLayout jPanel2_212Layout = new javax.swing.GroupLayout(jPanel2_212);
        jPanel2_212.setLayout(jPanel2_212Layout);
        jPanel2_212Layout.setHorizontalGroup(
            jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_212Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_212Layout.createSequentialGroup()
                        .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_212)
                            .addComponent(jLabel1_212))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKH_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKH_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2_212Layout.createSequentialGroup()
                        .addComponent(jLabel3_212)
                        .addGap(55, 55, 55)
                        .addComponent(radioBtnNam_212)
                        .addGap(18, 18, 18)
                        .addComponent(radioBtnNu_212)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2_212Layout.createSequentialGroup()
                        .addComponent(jLabel4_212)
                        .addGap(18, 18, 18)
                        .addComponent(txtSDT_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2_212Layout.createSequentialGroup()
                        .addComponent(jLabel5_212)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1_212, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2_212Layout.setVerticalGroup(
            jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_212Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_212Layout.createSequentialGroup()
                        .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_212)
                            .addComponent(txtMaKH_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2_212)
                            .addComponent(txtTenKH_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3_212)
                            .addGroup(jPanel2_212Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioBtnNam_212)
                                    .addComponent(radioBtnNu_212)))))
                    .addGroup(jPanel2_212Layout.createSequentialGroup()
                        .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4_212)
                            .addComponent(txtSDT_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5_212)
                            .addComponent(jScrollPane1_212, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3_212.setBackground(new java.awt.Color(204, 255, 204));

        btnThem_212.setBackground(new java.awt.Color(153, 153, 255));
        btnThem_212.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem_212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/plus.png"))); // NOI18N
        btnThem_212.setText("Thêm");
        btnThem_212.setPreferredSize(new java.awt.Dimension(150, 28));

        bthSua_212.setBackground(new java.awt.Color(153, 153, 255));
        bthSua_212.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bthSua_212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sua.png"))); // NOI18N
        bthSua_212.setText("Sửa");
        bthSua_212.setPreferredSize(new java.awt.Dimension(150, 28));

        btnXoa_212.setBackground(new java.awt.Color(153, 153, 255));
        btnXoa_212.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa_212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/xoa.png"))); // NOI18N
        btnXoa_212.setText("Xóa");
        btnXoa_212.setPreferredSize(new java.awt.Dimension(150, 28));

        btnRefresh_212.setBackground(new java.awt.Color(153, 153, 255));
        btnRefresh_212.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh_212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/refresh.png"))); // NOI18N
        btnRefresh_212.setText("Làm mới");
        btnRefresh_212.setPreferredSize(new java.awt.Dimension(150, 28));

        javax.swing.GroupLayout jPanel3_212Layout = new javax.swing.GroupLayout(jPanel3_212);
        jPanel3_212.setLayout(jPanel3_212Layout);
        jPanel3_212Layout.setHorizontalGroup(
            jPanel3_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_212Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bthSua_212, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btnXoa_212, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRefresh_212, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnThem_212, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel3_212Layout.setVerticalGroup(
            jPanel3_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_212Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnThem_212, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bthSua_212, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa_212, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh_212, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnThietLapTTKH_212Layout = new javax.swing.GroupLayout(jpnThietLapTTKH_212);
        jpnThietLapTTKH_212.setLayout(jpnThietLapTTKH_212Layout);
        jpnThietLapTTKH_212Layout.setHorizontalGroup(
            jpnThietLapTTKH_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThietLapTTKH_212Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3_212, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jpnThietLapTTKH_212Layout.setVerticalGroup(
            jpnThietLapTTKH_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThietLapTTKH_212Layout.createSequentialGroup()
                .addGroup(jpnThietLapTTKH_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3_212, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2_212, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpnThongTinKH_212.setBackground(new java.awt.Color(204, 255, 204));
        jpnThongTinKH_212.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        jpnTimKiem_212.setBackground(new java.awt.Color(204, 255, 204));

        txtTimKiem_212.setPreferredSize(new java.awt.Dimension(71, 28));

        btnTimKiem_212.setBackground(new java.awt.Color(153, 153, 255));
        btnTimKiem_212.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem_212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/search.png"))); // NOI18N
        btnTimKiem_212.setText("Tìm kiếm");

        javax.swing.GroupLayout jpnTimKiem_212Layout = new javax.swing.GroupLayout(jpnTimKiem_212);
        jpnTimKiem_212.setLayout(jpnTimKiem_212Layout);
        jpnTimKiem_212Layout.setHorizontalGroup(
            jpnTimKiem_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimKiem_212Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem_212, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem_212)
                .addGap(19, 19, 19))
        );
        jpnTimKiem_212Layout.setVerticalGroup(
            jpnTimKiem_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimKiem_212Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTimKiem_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem_212, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblKhachHang_212.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3_212.setViewportView(tblKhachHang_212);

        jpnLoc_212.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6_212.setText("Lọc theo giới tính");

        cbxLoc_212.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jpnLoc_212Layout = new javax.swing.GroupLayout(jpnLoc_212);
        jpnLoc_212.setLayout(jpnLoc_212Layout);
        jpnLoc_212Layout.setHorizontalGroup(
            jpnLoc_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoc_212Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxLoc_212, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnLoc_212Layout.createSequentialGroup()
                .addComponent(jLabel6_212)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnLoc_212Layout.setVerticalGroup(
            jpnLoc_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoc_212Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6_212)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxLoc_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnThongTinKH_212Layout = new javax.swing.GroupLayout(jpnThongTinKH_212);
        jpnThongTinKH_212.setLayout(jpnThongTinKH_212Layout);
        jpnThongTinKH_212Layout.setHorizontalGroup(
            jpnThongTinKH_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinKH_212Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpnThongTinKH_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnTimKiem_212, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3_212))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnLoc_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jpnThongTinKH_212Layout.setVerticalGroup(
            jpnThongTinKH_212Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinKH_212Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnTimKiem_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3_212, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(jpnThongTinKH_212Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jpnLoc_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnThietLapTTKH_212, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnThongTinKH_212, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnThietLapTTKH_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnThongTinKH_212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthSua_212;
    private javax.swing.JButton btnRefresh_212;
    private javax.swing.JButton btnThem_212;
    private javax.swing.JButton btnTimKiem_212;
    private javax.swing.JButton btnXoa_212;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxLoc_212;
    private javax.swing.JLabel jLabel1_212;
    private javax.swing.JLabel jLabel2_212;
    private javax.swing.JLabel jLabel3_212;
    private javax.swing.JLabel jLabel4_212;
    private javax.swing.JLabel jLabel5_212;
    private javax.swing.JLabel jLabel6_212;
    private javax.swing.JPanel jPanel2_212;
    private javax.swing.JPanel jPanel3_212;
    private javax.swing.JScrollPane jScrollPane1_212;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3_212;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpnLoc_212;
    private javax.swing.JPanel jpnThietLapTTKH_212;
    private javax.swing.JPanel jpnThongTinKH_212;
    private javax.swing.JPanel jpnTimKiem_212;
    private javax.swing.JRadioButton radioBtnNam_212;
    private javax.swing.JRadioButton radioBtnNu_212;
    private javax.swing.JTable tblKhachHang_212;
    private javax.swing.JTextArea txtAreaDiaChi_212;
    private javax.swing.JTextField txtMaKH_212;
    private javax.swing.JTextField txtSDT_212;
    private javax.swing.JTextField txtTenKH_212;
    private javax.swing.JTextField txtTimKiem_212;
    // End of variables declaration//GEN-END:variables
}
