/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;

import MODEL.QL_DanhSachDonHang_203;
import SERVICE.QLThongKe_Service;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phank
 */
public class ThongKe_JPanelFrom extends javax.swing.JPanel {

    /**
     * Creates new form ThongKe
     */
   DefaultTableModel defaultTableModel;
    QLThongKe_Service qLThongKe_Service;
    QL_DanhSachDonHang_203 qL_SanPhamDaBan_203;
     
    public ThongKe_JPanelFrom() throws SQLException {
        initComponents();
        qLThongKe_Service = new QLThongKe_Service();
        qL_SanPhamDaBan_203 = new QL_DanhSachDonHang_203();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        hangDaBan.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Mã đơn hàng");
        defaultTableModel.addColumn("Tên sản phẩm");
        defaultTableModel.addColumn("Địa chỉ giao hàng");
        defaultTableModel.addColumn("Số lượng đặt");
        defaultTableModel.addColumn("Ngày tạo đơn hàng");
        setTableData(qLThongKe_Service.getAllL_SanPhamDaBan());
    }
 private void setTableData(List<QL_DanhSachDonHang_203> SanPhamDaBan) {
        
     for(QL_DanhSachDonHang_203 sanPhan : SanPhamDaBan){
         defaultTableModel.addRow(new Object[]{sanPhan.getMaDH_203(), sanPhan.getTenSP_203(), sanPhan.getDiaChiGiaoHang_203(), 
             sanPhan.getSoLuongDat_203(),sanPhan.getNgayTaoDonHang_203()});

     }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        doanhThuPN = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tongTien = new javax.swing.JLabel();
        doanhThu = new javax.swing.JLabel();
        thongKeDT = new javax.swing.JComboBox<>();
        khoHang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        thongKeSL = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TonKho = new javax.swing.JLabel();
        soLuongDaBan = new javax.swing.JLabel();
        daBan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hangDaBan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        doanhThuPN.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Thống Kê Doanh Thu");

        tongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tongTien.setText("Doanh thu :");

        doanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doanhThu.setForeground(new java.awt.Color(255, 0, 0));
        doanhThu.setText(".....");

        thongKeDT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...........", "Tất cả", "Samsung Galaxy S22 Ultra 5G", "iPhone 11", "OPPO Ren7 series", "iPhone 13 Pro", "iphone 12 Pro", "Bàn phím có dây Gaming Asus TUF K1", "Chuột không dây Gaming Asus TUF M4 WL", "Chuột có dây Gaming Asus Keris", "Bàn phím có dây DareU EK87 ", "Bàn phím cơ có dây Gaming Razer BlackWidow", "Chuột không dây Rapoo M20 Plus Đen", "Cáp Type C- Lightning Apple MM0A3", "Sạc Hydrus CS-TC027", "Cáp Type C Xmobile MU09-1000X", "Đế sạc không dây Mbest AC63F3", "Tai nghe Bluetooth AirPods 2 Apple MRXJ2", "Tai nghe Bluetooth AirPods 3 Apple MME73", "Tai nghe có dây Mozard DS510-WB", "Tai nghe Bluetooth Chụp Tai Kanen K6", "Tai nghe EP Gaming Asus Rog Cetra II Core", " " }));
        thongKeDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongKeDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout doanhThuPNLayout = new javax.swing.GroupLayout(doanhThuPN);
        doanhThuPN.setLayout(doanhThuPNLayout);
        doanhThuPNLayout.setHorizontalGroup(
            doanhThuPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doanhThuPNLayout.createSequentialGroup()
                .addGroup(doanhThuPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doanhThuPNLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(doanhThuPNLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(doanhThuPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        doanhThuPNLayout.setVerticalGroup(
            doanhThuPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doanhThuPNLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(thongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(doanhThuPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tongTien)
                    .addComponent(doanhThu))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        khoHang.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Kho Hàng");

        thongKeSL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".........", "Samsung Galaxy S22 Ultra 5G", "iPhone 11", "OPPO Ren7 series", "iPhone 13 Pro", "iphone 12 Pro", "Bàn phím có dây Gaming Asus TUF K1", "Chuột không dây Gaming Asus TUF M4 WL", "Chuột có dây Gaming Asus Keris", "Bàn phím có dây DareU EK87 ", "Bàn phím cơ có dây Gaming Razer BlackWidow", "Chuột không dây Rapoo M20 Plus Đen", "Cáp Type C- Lightning Apple MM0A3", "Sạc Hydrus CS-TC027", "Cáp Type C Xmobile MU09-1000X", "Đế sạc không dây Mbest AC63F3", "Tai nghe Bluetooth AirPods 2 Apple MRXJ2", "Tai nghe Bluetooth AirPods 3 Apple MME73", "Tai nghe có dây Mozard DS510-WB", "Tai nghe Bluetooth Chụp Tai Kanen K6", "Tai nghe EP Gaming Asus Rog Cetra II Core", " " }));
        thongKeSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongKeSLActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Ðã bán :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tồn kho :");

        TonKho.setForeground(new java.awt.Color(255, 0, 0));
        TonKho.setText(".....");

        soLuongDaBan.setForeground(new java.awt.Color(255, 0, 0));
        soLuongDaBan.setText(".....");

        javax.swing.GroupLayout khoHangLayout = new javax.swing.GroupLayout(khoHang);
        khoHang.setLayout(khoHangLayout);
        khoHangLayout.setHorizontalGroup(
            khoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khoHangLayout.createSequentialGroup()
                .addGroup(khoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(khoHangLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(khoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(khoHangLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(soLuongDaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(khoHangLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(khoHangLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(khoHangLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(thongKeSL, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        khoHangLayout.setVerticalGroup(
            khoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khoHangLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thongKeSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(khoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(soLuongDaBan))
                .addGap(43, 43, 43)
                .addGroup(khoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TonKho))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        daBan.setBackground(new java.awt.Color(153, 255, 153));

        hangDaBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(hangDaBan);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Danh sách đơn hàng");

        javax.swing.GroupLayout daBanLayout = new javax.swing.GroupLayout(daBan);
        daBan.setLayout(daBanLayout);
        daBanLayout.setHorizontalGroup(
            daBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(daBanLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        daBanLayout.setVerticalGroup(
            daBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daBanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(khoHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doanhThuPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(daBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(doanhThuPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(khoHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void thongKeSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongKeSLActionPerformed
       String hangTonKho = null;
       String daban=null;
       try {
           hangTonKho = Integer.toString(qLThongKe_Service.thongKeHangTonKho((String) thongKeSL.getSelectedItem()));
           daban= Integer.toString(qLThongKe_Service.thongKeSoLuongDaBan((String) thongKeSL.getSelectedItem()));
       } catch (SQLException ex) {
           Logger.getLogger(ThongKe_JPanelFrom.class.getName()).log(Level.SEVERE, null, ex);
       }
        TonKho.setText(hangTonKho);
        soLuongDaBan.setText(daban);
    }//GEN-LAST:event_thongKeSLActionPerformed

    private void thongKeDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongKeDTActionPerformed
      String doanhThuString = null;
          try {
              doanhThuString= Long.toString(qLThongKe_Service.ThongKeDoanhThu((String) thongKeDT.getSelectedItem()));
          } catch (SQLException ex) {
              Logger.getLogger(ThongKe_JPanelFrom.class.getName()).log(Level.SEVERE, null, ex);
          }
           doanhThu.setText(doanhThuString);  
    }//GEN-LAST:event_thongKeDTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TonKho;
    private javax.swing.JPanel daBan;
    private javax.swing.JLabel doanhThu;
    private javax.swing.JPanel doanhThuPN;
    private javax.swing.JTable hangDaBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel khoHang;
    private javax.swing.JLabel soLuongDaBan;
    private javax.swing.JComboBox<String> thongKeDT;
    private javax.swing.JComboBox<String> thongKeSL;
    private javax.swing.JLabel tongTien;
    // End of variables declaration//GEN-END:variables
}
