/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;

/**
 *
 * @author DELL
 */
public class TrangChu_JPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form TrangChu
     */
    public TrangChu_JPanelForm() {
        initComponents();
    }

    /**                                                  
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2_229 = new javax.swing.JLabel();
        jLabel1_229 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(856, 600));

        jPanel1.setBackground(new java.awt.Color(1, 64, 85));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2_229.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2_229.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_229.setText("Thiết bị công nghệ ");
        jPanel1.add(jLabel2_229, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 360, 80));

        jLabel1_229.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1_229.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_229.setText(" - Kết nối với tương lai");
        jPanel1.add(jLabel1_229, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 460, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/6123.jpg_wh860.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_229;
    private javax.swing.JLabel jLabel2_229;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
